# **DİZİLER**
Diziler, vektörlerin ve matrislerin genelleştirilmiş halidir. Vektörler tek, matrisler ise iki boyutlu dizilerdir. Diziler, tek tür veri içerebilir.İkiden fazla boyutu olan dizi oluşturmak için array() fonksiyonundan yararlanılır.


---




### Boş bir dizinin oluşturulması




array(data = NA, dim = length(data), dimnames = NULL)

In [1]:
#1 den 24 e kadar 2 satır,3 sütundan oluşan 4 matris oluşturmak için; sonuç doğru gösterilmiyor. 4 tablo gibi düşünebiliriz.
x <- array(1:24, dim = c(2, 3, 4))
x

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24

In [2]:
#4 matristen 3. matrisle çalışmak için, diğer matrislerde bu şekilde oluşur.

x[,,3]

[,1] [,2] [,3]
[1,] 13   15   17  
[2,] 14   16   18

In [3]:
vektor_a <- c(5, 9, 3)
vektor_b <- c(10, 11, 12, 13, 14, 15)
sonuc <- array(c(vektor_a, vektor_b), dim = c(3, 3, 2))
sonuc[,,1]
print("----------")
sonuc[2,,2]#2. matrisin sadece 2. satırını getirmek için

[,1] [,2] [,3]
[1,] 5    10   13  
[2,] 9    11   14  
[3,] 3    12   15

[1] "----------"


[1]  9 11 14

In [4]:
# bir dizinin oluşturulması
dizi1 <- array(rnorm(60, mean = 50, sd = 2), c(3, 4, 1))
dizi1

, , 1

         [,1]     [,2]     [,3]     [,4]
[1,] 49.76904 48.71778 50.41352 50.82406
[2,] 52.94428 47.56187 51.88250 50.50391
[3,] 48.30640 48.55562 48.63230 49.09500

In [9]:
# bir dizinin oluşturulması satır ve sütun isimleriyle oluşturulması
sütunAdlari <- c("C1", "C2", "C3", "C4")
satirAdlari <- c("S1", "S2", "S3")
matrisAdlari <- c("Matris")
dizi2 <- array(1:60, dim = c(3, 4, 1),
               dimnames = list(satirAdlari, sütunAdlari, matrisAdlari))
dizi2

, , Matris

   C1 C2 C3 C4
S1  1  4  7 10
S2  2  5  8 11
S3  3  6  9 12

Terminal yanlış oluşturdu oluşan doğru hali aşağıdaki gibidir.

In [6]:
## , , Matris
##
##    C1 C2 C3 C4
## S1  1  4  7 10
## S2  2  5  8 11
## S3  3  6  9 12

In [7]:
# tüm matrislerin 3. satırlarını seçmek için
dizi2[3,,]

C1 C2 C3 C4 
 3  6  9 12

In [8]:
# yalnızca 2. matrisin 3. satırını seçmek
dizi2[3,,2]

ERROR: Error in dizi2[3, , 2]: subscript out of bounds


In [ ]:
# yalnızca 1. matrisin 1. satırının 3. sütunundaki elemanı seçmek
dizi2[1, 3, 1]

In [ ]:
# 1. matrisi seçmek
dizi2[,,1]

In [ ]:
# dizi2'ye yeni eleman eklenmesi
dizi2[,,1] <- matrix(101:112, 3, 4)

In [ ]:
# dizi2'nin yeni halinin incelenmesi
dizi2